services:
  postgres:
    image: postgres:17.6-alpine3.22
    container_name: postgres_db
    env_file: -.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
